"""add user

Revision ID: 58637e84c653
Revises: f982b6d2ff1f
Create Date: 2024-12-07 18:47:01.260360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58637e84c653'
down_revision: Union[str, None] = 'f982b6d2ff1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('contact', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contact', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('group', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('group_name_key', 'group', type_='unique')
    op.create_unique_constraint('unique_group_user', 'group', ['name', 'user_id'])
    op.create_foreign_key(None, 'group', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_constraint('unique_group_user', 'group', type_='unique')
    op.create_unique_constraint('group_name_key', 'group', ['name'])
    op.drop_column('group', 'user_id')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
