"""Change back_ref to back_populates

Revision ID: e56af5c0733d
Revises: 4f4e40c991a7
Create Date: 2024-12-01 20:56:38.606926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56af5c0733d'
down_revision: Union[str, None] = '4f4e40c991a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
